/**
 * Pixel art as text: each string is a row, each character a pixel, '.' is
 * transparent. Icons use 'x' (drawn in currentColor); café items carry their
 * own palettes. Café ids match the unlock thresholds on the server.
 */

export interface CafeItem {
  id: string;
  name: string;
  at: number;
  palette: Record<string, string>;
  rows: string[];
}

export const ICONS: Record<string, string[]> = {
  play: ['x......', 'xxx....', 'xxxxx..', 'xxxxxxx', 'xxxxx..', 'xxx....', 'x......'],
  pause: ['xx..xx', 'xx..xx', 'xx..xx', 'xx..xx', 'xx..xx', 'xx..xx', 'xx..xx'],
  skip: ['x....xx', 'xx...xx', 'xxx..xx', 'xxxx.xx', 'xxx..xx', 'xx...xx', 'x....xx'],
  reset: ['.x.xxx..', 'xx....x.', 'xxx....x', '.......x', 'x......x', 'x......x', '.x....x.', '..xxxx..'],
  gear: ['...xx...', '.x.xx.x.', '..xxxx..', 'xxx..xxx', 'xxx..xxx', '..xxxx..', '.x.xx.x.', '...xx...'],
  close: ['x.....x', '.x...x.', '..x.x..', '...x...', '..x.x..', '.x...x.', 'x.....x'],
};

export const CAFE: CafeItem[] = [
  {
    id: 'sprout',
    name: 'Sprout',
    at: 1,
    palette: { G: '#7BC950', g: '#3E8948', r: '#E0925F', T: '#C4693D', t: '#8F4A2E' },
    rows: [
      '............',
      '.......GG...',
      '......GGGG..',
      '..GG..GGG...',
      '.GGGG.g.....',
      '..GGGgg.....',
      '.....g......',
      '..rrrrrrrr..',
      '..tTTTTTTt..',
      '...tTTTTt...',
      '...tTTTTt...',
      '....tttt....',
    ],
  },
  {
    id: 'lamp',
    name: 'Desk Lamp',
    at: 3,
    palette: { S: '#F2C94C', s: '#C9962E', y: '#FFF3B0', p: '#6D4C41', P: '#4E342E' },
    rows: [
      '............',
      '....SSSS....',
      '...SSSSSS...',
      '...SSSSSS...',
      '..SSSSSSSS..',
      '..ssssssss..',
      '.....yy.....',
      '.....pp.....',
      '.....pp.....',
      '.....pp.....',
      '...pppppp...',
      '..PPPPPPPP..',
    ],
  },
  {
    id: 'cat',
    name: 'Café Cat',
    at: 5,
    palette: { c: '#E8A04A', d: '#B8732E', e: '#1B1B1B', n: '#F48FB1' },
    rows: [
      '............',
      '..d.....d...',
      '..cd...dc...',
      '..ccccccc...',
      '..cecccec...',
      '..cccnccc...',
      '...ccccc....',
      '..cdcccdc...',
      '..ccccccc.d.',
      '..cdcccdc.c.',
      '..ccccccccc.',
      '..cc...cc...',
    ],
  },
  {
    id: 'books',
    name: 'Book Stack',
    at: 10,
    palette: { R: '#C0392B', r: '#8E2A20', B: '#2E86DE', b: '#1F5F9E', V: '#27AE60', v: '#1B7A43', w: '#EFEBE9', Y: '#F2C94C' },
    rows: [
      '............',
      '............',
      '............',
      '..RRRRRRRRw.',
      '..RRYYRRRRw.',
      '..rrrrrrrrr.',
      '.BBBBBBBBBw.',
      '.BBBBYYBBBw.',
      '.bbbbbbbbbb.',
      '..VVVVVVVVw.',
      '..VVYYVVVVw.',
      '..vvvvvvvvv.',
    ],
  },
  {
    id: 'moka',
    name: 'Moka Pot',
    at: 20,
    palette: { M: '#B0BEC5', m: '#607D8B', L: '#ECEFF1', k: '#546E7A' },
    rows: [
      '.....kk.....',
      '...mmmmmm...',
      '.mMMMMMMMM..',
      '...MLMMMMkk.',
      '...MLMMMM.k.',
      '....MMMM..k.',
      '....mmmm.k..',
      '...MMMMMM...',
      '..MLMMMMMM..',
      '..MLMMMMMM..',
      '..MMMMMMMM..',
      '..mmmmmmmm..',
    ],
  },
  {
    id: 'vinyl',
    name: 'Vinyl',
    at: 35,
    palette: { x: '#4A4A4A', K: '#262626', h: '#6B6B6B', R: '#E74C3C' },
    rows: [
      '....xxxx....',
      '..xxKKKKxx..',
      '.xKKKKKKKKx.',
      '.xKhKKKKKKx.',
      'xKhKKRRKKKKx',
      'xKKKRRRRKKKx',
      'xKKKRRRRKKKx',
      'xKKKKRRKKhKx',
      '.xKKKKKKhKx.',
      '.xKKKKKKKKx.',
      '..xxKKKKxx..',
      '....xxxx....',
    ],
  },
  {
    id: 'candle',
    name: 'Candle',
    at: 50,
    palette: { o: '#FF9F43', y: '#FFF3B0', k: '#3E2723', w: '#EFEBE9', W: '#BCAAA4', P: '#8D6E63', p: '#5D4037' },
    rows: [
      '.....oo.....',
      '....oyyo....',
      '....oyyo....',
      '.....oo.....',
      '.....kk.....',
      '....wwww....',
      '....wWww....',
      '....wwwW....',
      '....wwwW....',
      '....wwwW....',
      '..PPPPPPPP..',
      '...pppppp...',
    ],
  },
  {
    id: 'golden-mug',
    name: 'Golden Mug',
    at: 100,
    palette: { a: '#B8860B', G: '#F2C94C', y: '#FFF3B0' },
    rows: [
      '..........y.',
      '.........yyy',
      '.aaaaaaaa.y.',
      '.aGGGGGGa...',
      '.aGyGGGGaaa.',
      '.aGyGGGGa.a.',
      '.aGGGGGGa.a.',
      '.aGGGGGGa.a.',
      '.aGGGGGGaaa.',
      '.aGGGGGGa...',
      '.aGGGGGGa...',
      '..aaaaaa....',
    ],
  },
];
